FIX: #256: Relaunch browser on disconnect
gramener/gramex pull request #291
Opened 2020-09-15 17:30 UTC by mniyas

2020-09-15 18:05 UTC, mniyas commented
@sanand0 Please review. The failed test case is not related to this PR.

2020-09-16 06:33 UTC, sanand0 commented
Thanks @mniyas -- the test case failure is due to TwitterRESTHandler. I'll explore that later.

I'll review this, test it locally, and revert with changes if required by EOD. Else I'll merge.

2020-09-16 07:10 UTC, sanand0 requested changes
@mniyas I've suggested changes to this PR. The main thing is that the test case doesn't actually test the disconnection behavior. Please take a look. Happy to help if you have any questions. Thanks!

2020-09-16 07:10 UTC, sanand0 commented on tests/test_capturehandler.py
> +        self.check_img(result.content)
I don't think this really checks if the browser restarts after disconnecting. This saves the file, and THEN disconnects. After that, we're not really testing anything.

We should disconnect, and then request ANOTHER file. That'll prove that it's able to reconnect.

2020-09-16 07:10 UTC, sanand0 commented on gramex/apps/capture/chromecapture.js
> +  if (url.parse(q.url, true).query._test_disconnect == 1){
I would suggest using just `if (q._test_disconnect) {`

`_test_disconnect` will get passed as part of `q` itself, not the URL encoded. So this code block can just be

```js
if (q._test_disconnect) {
  console.log('Disconnecting Chrome')
  browser.disconnect()
}
```

2020-09-16 07:10 UTC, sanand0 commented on gramex/apps/capture/chromecapture.js
> +    browser = await browser_setup(args)
We need to make another check here. If `browser` is undefined, OR if `browser` is disconnected, we should run this setup.

2020-09-16 07:10 UTC, sanand0 commented on gramex/apps/capture/chromecapture.js
> +const browser_setup = async (args) => {
Since this function is used only once, you can write it inline. No need for a separate function.

2020-09-16 07:10 UTC, sanand0 commented on gramex/apps/capture/chromecapture.js
> +const url = require('url')
I believe this won't be required. In a comment below, I suggest that we just use `q._test_disconnect` instead of `url.parse`

2020-09-17 16:37 UTC, mniyas commented
@sanand0 Please note the change in test case

2020-09-22 04:21 UTC, sanand0 commented
Thanks @mniyas -- I'll review this today

2020-10-03 11:53 UTC, sanand0 commented
Closed via 1698689

2020-10-03 11:53 UTC, closed without merging